In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [8]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [10]:
a = np.random.randn(10)
a

array([-0.92156477,  1.06405093, -1.40691376, -0.61924708, -2.28207811,
        0.13385431, -0.6645595 , -0.7724879 ,  1.91983996, -0.44839553])

In [11]:
b = np.random.randn(10)
b

array([-0.8591623 ,  0.1009984 ,  0.05732434, -0.04476036,  0.95058191,
        0.81754137,  0.29975661,  1.5427078 , -0.42660987,  0.89162764])

###binary functions

In [17]:
print np.add(a,b)
print np.maximum(a,b)

[-1.78072707  1.16504933 -1.34958942 -0.66400744 -1.33149619  0.95139568
 -0.36480289  0.77021989  1.49323009  0.44323211]
[-0.8591623   1.06405093  0.05732434 -0.04476036  0.95058191  0.81754137
  0.29975661  1.5427078   1.91983996  0.89162764]
